user  nginx;

events {
    worker_connections   1000;
}
http {
        upstream loadbalancer {
          server ecommercesite1:5001;
          server ecommercesite2:5002;
          server ecommercesite3:5003;
        }
        server {
              listen 80;
              location / {
                proxy_pass http://loadbalancer;
              }
        }
}