user  nginx;

events {
    worker_connections   1000;
}
http {
        upstream loadbalancer {
          server 192.168.10.248:5001;
          server 192.168.10.248:5002;
          server 192.168.10.248:5003;
        }
        server {
              listen 80;
              location / {
                proxy_pass http://loadbalancer;
              }
        }
}